apiVersion: v1
kind: Service
metadata:
  name: deploy-react-kubernetes-service
  labels:
    app: app
spec:
  type: NodePort
  ports:
  - port: 4444
    name: http
    protocol: TCP
    nodePort: 30080
    targetPort: 4444
  selector:
    app: app